### ISSUE TITLE
Time and voltage vectors somehow overwritten?

### ISSUE THREAD

**Issue by liameirose** [liameirose/bme590hrm#5]
Hi all,
My code was working fine, but I added a metrics dictionary and it seems to have overwritten my time and voltage vectors. Attached is my debugging screenshot. I am not sure how it is overwriting these vectors because even when I comment the metrics dictionary out the error still persists. 

<img width="1215" alt="screen shot 2018-10-20 at 6 11 55 pm" src="https://user-images.githubusercontent.com/42786410/47261012-2b35e200-d494-11e8-97ba-ba66671267df.png">

**Comment by mlp6** [comment]
Can you write a test for this function that fails on this error you are describing?

**Comment by mlp6** [comment]
Also, be aware that the test CSV files do *not* have column header names, so your `names` keyword input may not be working as you intend (something the test will pick up).

**Comment by liameirose** [comment]
I am trying to write a test to test whether my first value in my time array is a float, but I can't pull a value out of the time array. I am guessing this error also originates with how I am pulling in the data?

**Comment by mlp6** [comment]
As the debugging info in your PyCharm screenshot show, your `time` array is not actually an array (as you would like for it to be).  It is actually a dictionary!  This is related to how `numpy.read_csv()` is reading in the data.  You are wanting it to read in one column as an array, but that is not how it is working (see my previous comment).  The reason I could use your test is to see what is being passed in as an input for `filepath` and what the memory space looks like when that function is being called.

**Comment by liameirose** [comment]
Oh okay gotcha. I think I fixed it with np.loadtext and they are arrays now. Onto the next step! Thank you for your help!
